/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Albumn: typeof import('./src/views/Albumn.vue')['default']
    AlbumnItem: typeof import('./src/views/AlbumnItem.vue')['default']
    AnswerComment: typeof import('./src/fragments/comment/AnswerComment.vue')['default']
    BuryComment: typeof import('./src/fragments/comment/BuryComment.vue')['default']
    Catalog: typeof import('./src/components/Catalog.vue')['default']
    Comment: typeof import('./src/fragments/comment/Comment.vue')['default']
    DeleteComment: typeof import('./src/fragments/comment/DeleteComment.vue')['default']
    DiggComment: typeof import('./src/fragments/comment/DiggComment.vue')['default']
    EditComment: typeof import('./src/fragments/comment/EditComment.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpCircleCheck: typeof import('~icons/ep/circle-check')['default']
    IEpCircleClose: typeof import('~icons/ep/circle-close')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpPictureRounded: typeof import('~icons/ep/picture-rounded')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    MarkList: typeof import('./src/views/MarkList.vue')['default']
    PostComment: typeof import('./src/fragments/comment/PostComment.vue')['default']
    PostDetail: typeof import('./src/views/PostDetail.vue')['default']
    PostList: typeof import('./src/views/PostList.vue')['default']
    PostsByArchive: typeof import('./src/views/PostsByArchive.vue')['default']
    PostsByCalendar: typeof import('./src/views/PostsByCalendar.vue')['default']
    PostsByMark: typeof import('./src/views/PostsByMark.vue')['default']
    PostsBySort: typeof import('./src/views/PostsBySort.vue')['default']
    PostsItem: typeof import('./src/fragments/PostsItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopHeader: typeof import('./src/fragments/TopHeader.vue')['default']
  }
}
