/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerComment: typeof import('./src/fragments/comment/AnswerComment.vue')['default']
    Archive: typeof import('./src/views/Archive.vue')['default']
    BuryComment: typeof import('./src/fragments/comment/BuryComment.vue')['default']
    Catalog: typeof import('./src/components/Catalog.vue')['default']
    Category: typeof import('./src/views/Category.vue')['default']
    Comment: typeof import('./src/fragments/comment/Comment.vue')['default']
    DeleteComment: typeof import('./src/fragments/comment/DeleteComment.vue')['default']
    DiggComment: typeof import('./src/fragments/comment/DiggComment.vue')['default']
    EditComment: typeof import('./src/fragments/comment/EditComment.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    Home: typeof import('./src/views/Home.vue')['default']
    Label: typeof import('./src/views/Label.vue')['default']
    LabelList: typeof import('./src/views/LabelList.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    Navigation: typeof import('./src/fragments/Navigation.vue')['default']
    PhotoDetail: typeof import('./src/views/PhotoDetail.vue')['default']
    Photos: typeof import('./src/views/Photos.vue')['default']
    PostComment: typeof import('./src/fragments/comment/PostComment.vue')['default']
    PostDetail: typeof import('./src/views/PostDetail.vue')['default']
    PostItem: typeof import('./src/fragments/PostItem.vue')['default']
    Posts: typeof import('./src/views/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topic: typeof import('./src/components/Topic.vue')['default']
    Zone: typeof import('./src/views/Zone.vue')['default']
  }
}
