/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Albumn: typeof import('./src/views/Albumn.vue')['default']
    AlbumnItem: typeof import('./src/views/AlbumnItem.vue')['default']
    AnswerComment: typeof import('./src/fragments/comment/AnswerComment.vue')['default']
    BuryComment: typeof import('./src/fragments/comment/BuryComment.vue')['default']
    Catalog: typeof import('./src/components/Catalog.vue')['default']
    Comment: typeof import('./src/fragments/comment/Comment.vue')['default']
    DeleteComment: typeof import('./src/fragments/comment/DeleteComment.vue')['default']
    DiggComment: typeof import('./src/fragments/comment/DiggComment.vue')['default']
    EditComment: typeof import('./src/fragments/comment/EditComment.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    LabelList: typeof import('./src/views/LabelList.vue')['default']
    NavHeader: typeof import('./src/fragments/NavHeader.vue')['default']
    PostComment: typeof import('./src/fragments/comment/PostComment.vue')['default']
    PostDetail: typeof import('./src/views/PostDetail.vue')['default']
    PostItem: typeof import('./src/fragments/PostItem.vue')['default']
    PostList: typeof import('./src/views/PostList.vue')['default']
    PostsByArchive: typeof import('./src/views/PostsByArchive.vue')['default']
    PostsByCalendar: typeof import('./src/views/PostsByCalendar.vue')['default']
    PostsByLabel: typeof import('./src/views/PostsByLabel.vue')['default']
    PostsBySort: typeof import('./src/views/PostsBySort.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextRender: typeof import('./src/components/TextRender.vue')['default']
    Welcome: typeof import('./src/views/Welcome.vue')['default']
  }
}
